imports:
 - { resource: security.yml }
 - { resource: services.yml }

#==Symfony Standard
#===Framework
framework:
 csrf_protection: true
 default_locale: '%locale'
 #esi:    ~
 form:   true
 router:
  resource: '%kernel.root_dir%/config/routing.yml'
  strict_requirements: '%kernel.debug'
 secret:    %secret%
 #translator:   {fallback: %locale%}
 validation:   {enable_annotations: true}
 templating:   {engines: ['twig']} #assets_version: SomeVersionScheme
 trusted_proxies:
 session: ~

#===Assetic
assetic:
 bundles: []
 debug: %kernel.debug%
 use_controller: false
 # java: /usr/bin/java
 filters:
  cssrewrite: ~
  yui_css:
   jar: '%kernel.root_dir%/../vendor/yuicompressor/build/yuicompressor-2.4.8pre.jar'

#===Doctrine
doctrine:
 dbal:
  charset:  UTF8
  dbname:   %database_name%
  driver:   %database_driver%
  host:  %database_host%
  password: %database_password%
  port:  %database_port%
  user:  %database_user%
 orm:
  auto_generate_proxy_classes: %kernel.debug%
  auto_mapping: true

#===Twig
twig:
 debug: %kernel.debug%
 strict_variables: '%kernel.debug%'

#===Swiftmailer
swiftmailer:
 host:   %mailer_host%
 username:  %mailer_user%
 password:  %mailer_password%
 spool: {type: memory}
 transport: %mailer_transport%


#==TJM
tjm_base:
 page_wraps:
  full: ":base:skeletons/full.html.twig"
