tjmBasePage:
 pattern:  /
 defaults: { _controller: "TJMBaseBundle:Page:index" }

tjmBasePageShow:
 pattern:  /{id}/show
 defaults: { _controller: "TJMBaseBundle:Page:show" }

tjmBasePageNew:
 pattern:  /new
 defaults: { _controller: "TJMBaseBundle:Page:new" }

tjmBasePageCreate:
 pattern:  /create
 defaults: { _controller: "TJMBaseBundle:Page:create" }
 requirements: { _method: post }

tjmBasePageEdit:
 pattern:  /{id}/edit
 defaults: { _controller: "TJMBaseBundle:Page:edit" }

tjmBasePageUpdate:
 pattern:  /{id}/update
 defaults: { _controller: "TJMBaseBundle:Page:update" }
 requirements: { _method: post }

tjmBasePageDelete:
 pattern:  /{id}/delete
 defaults: { _controller: "TJMBaseBundle:Page:delete" }
 requirements: { _method: post }
